name: Build .NET MAUI
on: [ workflow_dispatch ]
concurrency:
  group: workflow
  cancel-in-progress: true
env:
  RELEASE_TAG: Canary-MAUI
jobs:
  windowsBuild:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install Workloads
        run: |
          dotnet workload install maui
      - name: Publish Project
        run: |
          dotnet publish -f net6.0-windows10.0.19041.0 -c Release -p:GenerateAppxPackageOnBuild=true -p:AppxPackageDir=..\packages\
          $artifact = (Get-ChildItem packages/*_Test/*.msix).FullName | Select-Object -First 1
          New-Item -ItemType Directory artifacts
          Move-Item $artifact artifacts/${{ github.event.repository.name }}_windows.msix
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: artifacts
  androidBuild:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 11
      - name: Install Workloads
        run: |
          dotnet workload install maui
          dotnet workload install android
      - name: Publish Project
        run: |
          dotnet publish -f net6.0-android -c Release -o build
          $artifact = (Get-ChildItem build/*.apk).FullName | Select-Object -First 1
          New-Item -ItemType Directory artifacts
          Move-Item $artifact artifacts/${{ github.event.repository.name }}_android.apk
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: artifacts
  release:
    needs: [ windowsBuild, androidBuild ]
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Packages
          path: artifacts
      - id: artifacts
        name: Check Artifacts
        run: |
          $artifacts = (Get-ChildItem -Recurse -File artifacts).FullName
          $artifactList = ""
          foreach ($artifact in $artifacts) {
            if ($artifactList.Length -gt 0) {
              $artifactList += ","
            }
            $artifactList += $artifact
          }
          Write-Output "::set-output name=RELEASE_ARTIFACTS::$artifactList"
      - name: Delete (Existing) Release Tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
      - name: Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.artifacts.outputs.RELEASE_ARTIFACTS }}
          prerelease: true
          tag: ${{ env.RELEASE_TAG }}
          commit: ${{ github.event.repository.default_branch }}