name: Build WinAppSdk
on: # change this when using this in a project
  push:
    paths:
      - .github/workflows/build-winappsdk.yml
  workflow_dispatch:
concurrency:
  group: build-winappsdk
  cancel-in-progress: true
env: # change these settings when using this in a project
  TARGET_BRANCH: template/winappsdk # use this instead: ${{ github.event.repository.default_branch }}
  PROJECT_FILE: ActionsPlayground/ActionsPlayground.csproj
  RELEASE_TAG: Canary-WinAppSdk
  ARTIFACT_NAME: Canary
  # SIGNING_CERTIFICATE: # base64 string of certificate file
  # SIGNING_KEY: # password of certificate
jobs:
  build:
    strategy:
      matrix:
        platform: [ x86, x64, arm64 ]
    continue-on-error: true
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
          submodules: recursive
          lfs: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - id: certificate
        name: Install Certificate
        run: |
          if (![string]::IsNullOrEmpty("${{ env.SIGNING_CERTIFICATE }}") -and ![string]::IsNullOrEmpty("${{ env.SIGNING_KEY }}")) {
            $bytes = [System.Convert]::FromBase64String("${{ env.SIGNING_CERTIFICATE }}")
            [IO.File]::WriteAllBytes("certificate.pfx", $bytes)
            $password = ConvertTo-SecureString ${{ env.SIGNING_KEY }} -AsPlainText
            Import-PfxCertificate certificate.pfx -CertStoreLocation "Cert:\CurrentUser\My" -Password $password
            $thumbprint = (Get-PfxCertificate Certificate.pfx -Password $password).Thumbprint
            Write-Output "::set-output name=SIGNING_THUMBPRINT::$thumbprint"
          }
      - name: Publish Project
        run: |
          if ([string]::IsNullOrEmpty("${{ steps.certificate.outputs.SIGNING_THUMBPRINT }}")) {
            dotnet publish ${{ env.PROJECT_FILE }} -c Release -p:Platform=${{ matrix.platform }} -p:RuntimeIdentifier=win10-${{ matrix.platform }} -p:WindowsAppSdkSelfContained=true -p:GenerateAppxPackageOnBuild=true -p:AppxPackageDir=${{ github.workspace }}/packages/
          } else {
            dotnet publish ${{ env.PROJECT_FILE }} -c Release -p:Platform=${{ matrix.platform }} -p:RuntimeIdentifier=win10-${{ matrix.platform }} -p:WindowsAppSdkSelfContained=true -p:GenerateAppxPackageOnBuild=true -p:AppxPackageSigningEnabled=true -p:PackageCertificateThumbprint=${{ steps.certificate.outputs.SIGNING_THUMBPRINT }} -p:AppxPackageDir=${{ github.workspace }}/packages/
          }
          $artifact = (Get-ChildItem ${{ github.workspace }}/packages/*_Test/*.msix).FullName | Select-Object -First 1
          New-Item -ItemType Directory artifacts
          Move-Item $artifact artifacts/${{ github.event.repository.name }}_${{ matrix.platform }}.msix
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifacts
  release:
    needs: build
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: artifacts
      - id: artifacts
        name: Check Artifacts
        run: |
          $artifacts = (Get-ChildItem -Recurse -File artifacts).FullName
          $artifactList = ""
          foreach ($artifact in $artifacts) {
            if ($artifactList.Length -gt 0) {
              $artifactList += ","
            }
            $artifactList += $artifact
          }
          Write-Output "::set-output name=RELEASE_ARTIFACTS::$artifactList"
      - name: Delete (Existing) Release Tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
      - name: Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.artifacts.outputs.RELEASE_ARTIFACTS }}
          prerelease: true
          tag: ${{ env.RELEASE_TAG }}
          commit: ${{ env.TARGET_BRANCH }}