name: .NET Deployment
run-name: ".NET Deployment #${{ github.run_number }}"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

### Configuration ###

on: [ push, workflow_dispatch ]
env:
  TARGET_BRANCH: template/dotnet # ${{ github.event.repository.default_branch }}
  PROJECT_FILE: ActionsPlayground.sln
  RELEASE_TAG: DotNet

### Configuration ###

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
          lfs: true
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
      - name: Publish Project
        run: |
          dotnet publish ${{ env.PROJECT_FILE }} --configuration Release --output build
          $artifacts = (Get-ChildItem -Path build/*).FullName
          New-Item -Path artifacts -ItemType Directory
          Compress-Archive -Path $artifacts -DestinationPath artifacts/${{ github.event.repository.name }}.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Output
          path: artifacts
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Output
          path: artifacts
      - id: artifacts
        name: Check Artifacts
        run: |
          $artifacts = (Get-ChildItem -Path artifacts -File -Recurse).FullName
          $artifactList = ""
          foreach ($artifact in $artifacts) {
            if ($artifactList.Length -gt 0) {
              $artifactList += ","
            }
            $artifactList += $artifact
          }
          echo "ARTIFACTS=$artifactList" >> $env:GITHUB_ENV
      - name: Delete (Existing) Releases
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          delete_release: true
          delete_draft_release: true
      - name: Release Artifacts
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: ${{ steps.artifacts.outputs.ARTIFACTS }}
          prerelease: true
          commit: ${{ env.TARGET_BRANCH }}
          tag: ${{ env.RELEASE_TAG }}