name: .NET Deployment
run-name: ".NET Deployment #${{ github.run_number }}"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

### Configuration ###

on:
  push:
    paths:
      - .github/workflows/dotnet.yml
  workflow_dispatch:
env:
  TARGET_BRANCH: template/dotnet # ${{ github.event.repository.default_branch }}
  PROJECT_FILE: ActionsPlayground.sln
  RELEASE_TAG: DotNet

### Configuration ###

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
          lfs: true
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
      - name: Publish Project
        run: |
          dotnet publish ${{ env.PROJECT_FILE }} --configuration Release --output build
          $artifacts = (Get-ChildItem -Path build/*).FullName
          New-Item -Path artifacts -ItemType Directory
          Compress-Archive -Path $artifacts -DestinationPath artifacts/${{ github.event.repository.name }}.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Output
          path: artifacts
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Output
          path: artifacts
      - name: Delete (Existing) Releases
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          delete_release: true
          delete_draft_release: true
      - name: Release Artifacts
        uses: softprops/action-gh-release@v0.1.15
        with:
          target_commitish: ${{ env.TARGET_BRANCH }}
          tag_name: ${{ env.RELEASE_TAG }}
          prerelease: true
          files: artifacts/*