name: .NET MAUI Deployment
run-name: ".NET MAUI Deployment #${{ github.run_number }}"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  push:
    paths:
      - .github/workflows/dotnet-maui.yml
  workflow_dispatch:
jobs:
  main:
    uses: dentolos19/ActionsPlayground/.github/workflows/reusables/dotnet-maui.yml@main
    with:
      TARGET_BRANCH: template/maui # ${{ github.event.repository.default_branch }}
      PROJECT_FILE: ActionsPlayground.sln
      RELEASE_TAG: DotNetMaui
      WINDOWS_TARGET_FRAMEWORK: net6.0-windows10.0.19041.0
      ANDROID_TARGET_FRAMEWORK: net6.0-android
      # SIGNING_CERTIFICATE: # your pfx file encoded in base64 string
      # SIGNING_KEY: # your key for accessing the certificate