name: .NET MAUI Deployment
run-name: ".NET MAUI Deployment #${{ github.run_number }}"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

### Configuration ###

on: [ push, workflow_dispatch ]
env:
  TARGET_BRANCH: template/maui # ${{ github.event.repository.default_branch }}
  PROJECT_FILE: ActionsPlayground.sln
  WINDOWS_TARGET_FRAMEWORK: net6.0-windows10.0.19041.0
  ANDROID_TARGET_FRAMEWORK: net6.0-android
  # SIGNING_CERTIFICATE: # certificate.pfx file encoding in base64
  # SIGNING_KEY: # key string for signing with certificate
  RELEASE_TAG: DotNetMaui

### Configuration ###

jobs:
  windowsBuild:
    name: Build for Windows
    continue-on-error: true
    runs-on: windows-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
          lfs: true
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
      - name: Install .NET Workloads
        run: |
          dotnet workload install maui
      - id: certificate
        name: Install Signing Certificate
        run: |
          if (![string]::IsNullOrEmpty("${{ env.SIGNING_CERTIFICATE }}") -and ![string]::IsNullOrEmpty("${{ env.SIGNING_KEY }}")) {
            $bytes = [System.Convert]::FromBase64String("${{ env.SIGNING_CERTIFICATE }}")
            [IO.File]::WriteAllBytes("certificate.pfx", $bytes)
            $password = ConvertTo-SecureString ${{ env.SIGNING_KEY }} -AsPlainText
            Import-PfxCertificate certificate.pfx -CertStoreLocation "Cert:\CurrentUser\My" -Password $password
            $thumbprint = (Get-PfxCertificate Certificate.pfx -Password $password).Thumbprint
            Write-Output -InputObject "SIGNING_THUMBPRINT=$thumbprint" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }
      - name: Publish Project
        run: |
          if ([string]::IsNullOrEmpty("${{ steps.certificate.outputs.SIGNING_THUMBPRINT }}")) {
            dotnet publish ${{ env.PROJECT_FILE }} --framework ${{ env.WINDOWS_TARGET_FRAMEWORK }} --configuration Release -p:GenerateAppxPackageOnBuild=true -p:AppxPackageDir=${{ github.workspace }}/packages/
          } else {
            dotnet publish ${{ env.PROJECT_FILE }} --framework ${{ env.WINDOWS_TARGET_FRAMEWORK }} --configuration Release -p:GenerateAppxPackageOnBuild=true -p:AppxPackageSigningEnabled=true -p:PackageCertificateThumbprint=${{ steps.certificate.outputs.SIGNING_THUMBPRINT }} -p:AppxPackageDir=${{ github.workspace }}/packages/
          }
          $artifact = (Get-ChildItem ${{ github.workspace }}/packages/*_Test/*.msix).FullName | Select-Object -First 1
          New-Item -Path artifacts -ItemType Directory
          Move-Item -Path $artifact -DestinationPath artifacts/${{ github.event.repository.name }}_windows.msix
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Output
          path: artifacts
  androidBuild:
    name: Build for Android
    continue-on-error: true
    runs-on: windows-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_BRANCH }}
          lfs: true
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 11
      - name: Install .NET Workloads
        run: |
          dotnet workload install maui
          dotnet workload install android
      - name: Publish Project
        run: |
          dotnet publish ${{ env.PROJECT_FILE }} --framework ${{ env.ANDROID_TARGET_FRAMEWORK }} --configuration Release --output build
          $artifact = (Get-ChildItem build/*.apk).FullName | Select-Object -First 1
          New-Item -Path artifacts -ItemType Directory
          Move-Item -Path $artifact -DestinationPath artifacts/${{ github.event.repository.name }}_android.apk
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Output
          path: artifacts
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Output
          path: artifacts
      - name: Release Artifacts
        uses: softprops/action-gh-release@v0.1.15
        with:
          target_commitish: ${{ env.TARGET_BRANCH }}
          tag_name: ${{ env.RELEASE_TAG }}
          prerelease: true
          files: artifacts/*