name: .NET Deployment
run-name: ".NET Deployment #${{ github.run_number }}"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
on:
  push:
    paths:
      - .github/workflows/dotnet.yml
  workflow_dispatch:
jobs:
  main:
    uses: dentolos19/ActionsPlayground/.github/workflows/REUSABLE-dotnet.yml@main
    with:
      TARGET_BRANCH: template/dotnet # ${{ github.event.repository.default_branch }}
      PROJECT_FILE: ActionsPlayground.sln
      RELEASE_TAG: DotNet