name: Reusable Workflow for Unity Deployment
on:
  workflow_call:
    inputs:
      TARGET_BRANCH:
        type: string
        default: ${{ github.event.repository.default_branch }}
      PROJECT_DIRECTORY:
        type: string
        default: .
    secrets:
      UNITY_LICENSE:
        required: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.TARGET_BRANCH }}
          lfs: true
          submodules: recursive
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Build Project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          projectPath: ${{ inputs.PROJECT_DIRECTORY }}
          buildName: ${{ github.event.repository.name }}
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/WebGL/${{ github.event.repository.name }}
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1